/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_echo_LocalEchoActivity_ClientTask */

#ifndef _Included_com_apress_echo_LocalEchoActivity_ClientTask
#define _Included_com_apress_echo_LocalEchoActivity_ClientTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
