/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_echo_EchoServerActivity_ServerTask */

#ifndef _Included_com_apress_echo_EchoServerActivity_ServerTask
#define _Included_com_apress_echo_EchoServerActivity_ServerTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
